### PR TITLE
Fix issues with Impropriety Among Thieves

### LINKED ISSUE #1165: Issues with Impropriety Among Thieves
Multiple bug reports of Impropriety Among Thieves not working correctly - one report was that units didn't return correctly, another was that the effect may have returned a to the field from being in hand.

These aren't validated but should be investigated and we should add more test cases. One very likely cause is that one of the swapped units is going to discard or some other zone, and that causes some kind of exception when the delayed effects resolve which blocks the other unit's delayed effect from resolving.

### PR DESCRIPTION
**Pull request by moyerr**
Fixes #1165

### Test Cases Added:

- Event fizzles if there is no ready friendly non-leader unit
- Event fizzles if there is no ready enemy non-leader unit
- A unit is defeated after exchange of control
- A unit is returned to hand after exchange of control
- A unit changes control again after initial exchange of control
- Both units are defeated, one of which moves to the resource zone
- Both units are returned to hand

### CODE REVIEW

**Comment by moyerr** [comment]
This should have one more test case for when a unit becomes a leader unit due to leader pilot upgrade after #895

File: server/game/cards/03_TWI/events/ImproprietyAmongThieves.ts [hunk 1]
```diff
@@ -20,44 +20,41 @@ export default class ImproprietyAmongThieves extends EventCard {
                     cardTypeFilter: WildcardCardType.NonLeaderUnit,
                     zoneFilter: WildcardZoneName.AnyArena,
                     cardCondition: (card) => card.canBeExhausted() && !card.exhausted,
-                },
-                enemyUnit: {
-                    dependsOn: 'friendlyUnit',
```
Comment (AMMayberry1) [inline server/game/cards/03_TWI/events/ImproprietyAmongThieves.ts:25]: I think we still need this, otherwise it would work when only one player has a unit. I think we don't have tests for that yet, which we definitely need to add - specifically, test cases that it whiffs if there's only a friendly unit and no enemy unit and vice versa

Comment (moyerr) [reply server/game/cards/03_TWI/events/ImproprietyAmongThieves.ts:25]: Right right, good call

**Review by AMMayberry1 — APPROVED** [review]
