### PR TITLE
Prevent willDefeat triggers if event has been replaced

### LINKED ISSUE #1096: Shoot Down second part ability trigger if shield is destroyed
**Describe the bug**
Shoot Down deal 2 damage if shield was defeat but it should not

**To Reproduce**
Add this tests : 
```
  it('should not deal damage to base if shield was defeat', function () {
                const { context } = contextRef;

                context.player1.passAction();
                context.player2.clickCard(context.momentOfPeace);
                context.player2.clickCard(context.tielnFighter);

                context.player1.clickCard(context.shootDown);
                context.player1.clickCard(context.tielnFighter);

                expect(context.player2).toBeActivePlayer();
            });
```

### PR DESCRIPTION
**Pull request by Frugghi**
Fixes #1096

### CODE REVIEW

File: server/game/core/event/GameEvent.ts [hunk 1]
```diff
@@ -193,4 +193,16 @@ export class GameEvent {
         }
         return undefined;
     }
+
+    public get resolvedEvents(): GameEvent[] {
```
Comment (AMMayberry1) [inline server/game/core/event/GameEvent.ts:197]: Could we add a clarifying jsdoc comment to this and `AbilityContext.resolvedEvents` explaining that it is returning the events that actually resolved, which might mean it's returning the replacement effect. And / or rename this to something longer like `getEventsOrReplacedEvents()`

**Review by AMMayberry1 — APPROVED** [review]
