### PR TITLE
Fix abilities triggered by defeating units while attacking

### LINKED ISSUE #1155: "Attacks and defeats" abilities do not trigger from on-attack abilities
It has been ruled that if a defending enemy unit is triggered by an on-attack ability such as e.g. Sabine1 unit or Fallen Lightsaber, that should trigger abilities saying "when a unit attacks and defeats...". This is currently not working right, we need to build a solution and then apply to all existing cards.

This is high-priority due to the Revan leader.

### PR DESCRIPTION
**Pull request by Frugghi**
Fixes #1155

### CODE REVIEW

File: server/game/gameSystems/DefeatCardSystem.ts [hunk 1]
```diff
@@ -138,4 +137,21 @@ export class DefeatCardSystem<TContext extends AbilityContext = AbilityContext,
 
         this.addLastKnownInformationToEvent(event, card);
     }
+
+    public static defeatSourceCard(event): Card | undefined {
```
Comment (AMMayberry1) [inline server/game/gameSystems/DefeatCardSystem.ts:141]: nit: our convention is to put static methods above the ctor

File: test/server/cards/05_LOF/leaders/DarthRevanScourgeOfTheOldRepublic.spec.ts [hunk 2]
```diff
@@ -210,6 +210,32 @@ describe('Darth Revan, Scourge of the Old Republic', function () {
...
+
+                context.player2.clickCard(context.cartelSpacer);
+
+                expect(context.player1).toHavePassAbilityPrompt('Exhaust this leader');
+                context.player1.clickPrompt('Trigger');
+
+                expect(context.avenger).toHaveExactUpgradeNames(['experience']);
+                expect(context.darthRevan.exhausted).toBe(true);
+            });
+
```
Comment (AMMayberry1) [inline test/server/cards/05_LOF/leaders/DarthRevanScourgeOfTheOldRepublic.spec.ts:238]: Apologies, thought of one more for completeness - let's test defeat with a gained ability from an upgrade like Fallen Lightsaber

**Review by AMMayberry1 — APPROVED** [review]
