### PR TITLE
[Bugfix] Bounty Hunter's Quarry can resolve during the regroup phase

### LINKED ISSUE #1067: Bounty Hunter's Quarry not working during regroup phase
Player report:

playing vs bossk green, they put a bounty hunter quarry on Fireball, and when fireball died in the regroup phase they got to see the cards but not play them

### PR DESCRIPTION
**Pull request by moyerr**
Fixes #1067 

### Notes

- Removed phase check in `PlayerAction.js` because it was preventing certain actions from being executed off a triggered ability during the regroup phase
- Added a simple case of collecting Bounty Hunter's Quarry during the regroup phase to `BountyHuntersQuarry.spec.ts`
- Added several more complex cases of chains of triggered abilities (all stemming from BHQ) to `RegroupPhase.spec.ts`

### CODE REVIEW

File: test/helpers/IntegrationHelper.js [hunk 1]
```diff
@@ -121,7 +125,7 @@ global.integration = function (definitions) {
                 let activePromptsText = playersWithUnresolvedPrompts.map((player) =>
                     `\n******* ${player.name.toUpperCase()} PROMPT *******\n${formatPrompt(player.currentPrompt(), player.currentActionTargets)}\n`
                 ).join('');
-
+                console.log(`** Unresolved prompt in ${context.game.currentPhase} phase`);
```
Comment (AMMayberry1) [inline test/helpers/IntegrationHelper.js:128]: Debug code?

Comment (moyerr) [reply test/helpers/IntegrationHelper.js:128]: Whoops, good catch! Removing now.

**Review by AMMayberry1 — APPROVED** [review]
